### ISSUE TITLE
你写的不对(OneDrive 和 sharepoint 有点不一样)

### ISSUE THREAD

**Issue by dnslin** [a1667834841/Onemanager-java#1]
你这样写是不支持sharepoint和OneDrive世纪互联的,另外我之前是用的mysql 我考虑了一下应该换成h2这种本地db会比较好一点
加油 我忙工作没时间写 靠你了

**Comment by dnslin** [comment]
而且索引 并不需要用到 ES 你在H2SQL 里面维护一张表就行了 
这张表的数据结构也很简单的 文件夹和文件 用不同的层级id进行关联就能做到
用户增删改的时候 向微软发起一次请求同时本地数据库也做一次改变
(这种情况适用于预先建立)

**Comment by a1667834841** [comment]
> 你这样写是不支持sharepoint和OneDrive世纪互联的,另外我之前是用的mysql 我考虑了一下应该换成h2这种本地db会比较好一点 加油 我忙工作没时间写 靠你了

我还没有了解你说的这两种，后面我会去了解的，数据库确实用h2方便一点，谢谢你的建议

**Comment by a1667834841** [comment]
> 而且索引 并不需要用到 ES 你在H2SQL 里面维护一张表就行了 这张表的数据结构也很简单的 文件夹和文件 用不同的层级id进行关联就能做到 用户增删改的时候 向微软发起一次请求同时本地数据库也做一次改变 (这种情况适用于预先建立)

其实我一开始只是想做成对文本文件的全文索引，方便对笔记做搜索，所以想使用es
